(() => {
  "use strict";
  const presentation = JSON.parse(document.getElementById("clineflow-presentation").textContent);
  const $ = (selector, root = document) => root.querySelector(selector);
  const esc = (value = "") => String(value).replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  const full = new Intl.NumberFormat();
  const compact = new Intl.NumberFormat(undefined, {notation: "compact", maximumFractionDigits: 1});
  const time = value => value ? new Date(value).toLocaleString() : "Not recorded";
  const humanize = value => String(value || "").replace(/^clineflow_/, "").replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());
  const statementText = value => {
    if (value === null || value === undefined) return "Not recorded";
    if (typeof value !== "object") return String(value);
    if (Array.isArray(value)) return value.map(statementText).filter(Boolean).join(" · ") || "Not recorded";
    for (const key of ["text", "summary", "title", "name", "criterion", "requirement", "description", "message", "label", "value"]) {
      if (value[key] !== undefined && value[key] !== null && typeof value[key] !== "object") return String(value[key]);
    }
    return Object.entries(value).map(([key, item]) => `${humanize(key)}: ${statementText(item)}`).join(" · ") || "Structured record";
  };
  const eventTitle = event => String(event?.title || event?.label || "Recorded event");
  const docs = presentation.documents || [];
  const docById = new Map(docs.map(item => [item.id, item]));
  const sourceIdForRef = ref => {
    const value = String(ref || "").replace(/^\.\.\//, "");
    return docs.find(doc => doc.path === value || doc.path.endsWith(`/${value.replace(/^knowledge\//, "")}`))?.id;
  };
  const copy = async value => {
    try { await navigator.clipboard.writeText(value); return true; }
    catch (_) { const input = document.createElement("textarea"); input.value = value; input.style.position = "fixed"; input.style.opacity = "0"; document.body.append(input); input.select(); const copied = document.execCommand("copy"); input.remove(); return copied; }
  };

  const now = presentation.now || {};
  const metrics = presentation.metrics || {};
  const timeline = presentation.timeline || [];
  const pulse = presentation.project_pulse || {};
  const estimate = presentation.delivery_estimate;
  const milestoneCards = (presentation.story?.milestones || []).map(item => `<li><time>${esc(time(item.at))}</time><strong>${esc(item.title || "Recorded milestone")}</strong></li>`).join("") || "<li><strong>Capture the first milestone to begin the story.</strong></li>";
  document.getElementById("app").innerHTML = `<main class="shell" id="main">
    <header class="topbar"><div class="brand"><span class="brand-mark">CF</span><span>Knowledge Visor / narrative view</span></div><div class="toolbar"><span class="pill">${presentation.report?.git?.dirty ? "Working tree · changed" : "Working tree · clean"}</span><button id="time-mode" type="button">Local time</button></div></header>
    <section class="hero"><article class="hero-main"><div><p class="eyebrow">Now / ${esc(time(presentation.generated_at))}</p><h1>${esc(now.headline || "Build the first durable project record")}</h1><p class="lede">${esc(now.summary || "Start by capturing what changed, why it matters, and the next move.")}</p></div>${presentation.onboarding?.empty ? `<aside class="onboarding"><span class="label">First useful capture</span><strong>${esc(presentation.onboarding.title)}</strong><p>${esc(presentation.onboarding.text)}</p></aside>` : ""}<div class="brief-grid"><article><span class="label">Current intent</span><p>${esc(now.intent || "No active goal recorded.")}</p></article><article><span class="label">Latest proof</span><p>${esc(now.latest_verification?.title || "No verification event recorded yet.")}</p></article><article><span class="label">Next move</span><p>${esc(now.next_move || "Capture the next deliberate move.")}</p></article></div></article><aside class="hero-side"><div class="metric"><span class="label">Knowledge sources</span><strong>${full.format(metrics.documents || 0)}</strong></div><div class="metric"><span class="label">Open attention items</span><strong>${full.format(now.unresolved_count || 0)}</strong></div><div class="metric"><span class="label">Latest activity</span><strong>${esc(now.latest_activity?.when ? new Date(now.latest_activity.when).toLocaleDateString(undefined,{month:"short",day:"numeric"}) : "—")}</strong></div></aside></section>
    <div class="grid">
      <section class="panel wide agentic-loop-panel"><div class="panel-head"><div><p class="eyebrow">Current Agentic Loop</p><h2>From intent to proof.</h2><p class="panel-copy">The active goal, decision boundary, next action, and evidence state—read as one operating loop.</p></div><span class="story-badge">Live context</span></div><ol id="agentic-loop" class="agentic-loop"></ol></section>
      <header class="section-intro"><p class="eyebrow">The narrative</p><h2>Understand before you inspect.</h2><p>Move from the current signal to its decisions, proof, and source record—without decoding the entire knowledge base first.</p></header>
      <section class="panel wide project-story-panel"><div class="panel-head"><div><h2>Project story</h2><p class="panel-copy">The turning points behind today’s decision, with direct source handoffs.</p></div><span class="story-badge">Narrative arc</span></div><div id="story-evolution"></div><div class="story-arc"><div id="story-cards" class="story-actions"></div><ol class="story-milestones">${milestoneCards}</ol></div></section>
      <section class="panel wide recent-story-panel"><div class="panel-head"><div><p class="eyebrow">Trajectory</p><h2>Recent story</h2><p class="panel-copy">Three meaningful beats first. The audit trail stays out of the way until you need it.</p></div><button class="text-action" id="timeline-toggle" type="button"></button></div><div id="recent-story" class="recent-story recent-beats"></div><div class="time-spine" id="time-spine" hidden></div></section>
      <section class="panel wide pulse-panel"><div class="panel-head"><div><p class="eyebrow">Trajectory / Project Pulse</p><h2>Change has a shape.</h2><p class="panel-copy">Committed change volume and tracked-tree growth. This is scope context, not a productivity score.</p></div><span class="story-badge">Git facts</span></div><div class="pulse-layout"><div id="pulse-chart" class="chart pulse-chart" role="img" aria-label="Committed change volume and tracked project footprint over time"></div><div id="pulse-summary" class="pulse-summary"></div></div><details class="pulse-details"><summary>Inspect committed change detail</summary><div id="pulse-details"></div></details></section>
      ${estimate ? `<section class="panel wide estimate-panel"><div class="panel-head"><div><p class="eyebrow">Planning model / Delivery Scenarios</p><h2>What the delivery model suggests.</h2><p class="panel-copy">A transparent agent estimate in two dimensions: engineering time and modeled cost.</p></div><span class="story-badge">Estimated</span></div><div id="delivery-estimate"></div></section>` : ""}
      <header class="section-intro"><p class="eyebrow">Decisions and proof</p><h2>What needs a human decision?</h2><p>Questions and verification are explicit. The visor never invents a productivity or health score.</p></header>
      <section class="panel"><div class="panel-head"><div><h2>Decision queue</h2><p class="panel-copy">What is open, why it matters, and the next deliberate move.</p></div></div><div class="signals" id="attention"></div></section>
      <section class="panel"><div class="panel-head"><div><h2>Evidence surface</h2><p class="panel-copy">Inspectable requirements and evidence.</p></div></div><div class="signals" id="evidence"></div></section>
      <header class="section-intro"><p class="eyebrow">Source</p><h2>Open the record when it matters.</h2><p>Search canonical ledgers, journals, and indexes. Structured YAML is readable before raw source is necessary.</p></header>
      <section class="panel wide explorer-panel"><div class="panel-head"><div><h2>Knowledge Explorer</h2><p class="panel-copy">Select a source, then choose guided context, JSON, or raw text.</p></div><div class="explorer-tools"><div class="document-filters" id="document-filters"><button class="active" data-filter="all" type="button">All</button><button data-filter="ledger" type="button">Ledgers</button><button data-filter="journal" type="button">Journals</button></div><input class="search" id="search" type="search" placeholder="Search decisions, evidence, journals…" aria-label="Search knowledge"></div></div><div class="documents"><nav class="document-list" id="document-list" aria-label="Knowledge documents"></nav><article class="document-body" id="document-body"></article></div></section>
    </div><footer class="footer"><span>Generated ${esc(presentation.generated_at)} · ${esc(presentation.report?.run_id)}</span><span>Local report · no browser network access</span></footer></main><dialog id="estimate-modal" class="pending-modal"></dialog>`;

  let utc = false, showFullTimeline = false, selectedDocument = null, activeFilter = "all";
  const formatTime = value => utc && value ? new Date(value).toISOString() : time(value);
  const openDocument = id => { selectedDocument = id; renderDocuments($("#search").value); renderDocumentPanel(docById.get(id)); };
  const sourceAction = ids => ids?.find(id => docById.has(id));
  const loop = presentation.agentic_loop || [];
  $("#agentic-loop").innerHTML = loop.map(item => { const source = sourceAction(item.source_ids); return `<li><span>${esc(item.step)}</span><div><p class="eyebrow">${esc(item.label)}</p><strong>${esc(item.text)}</strong></div>${source ? `<button class="text-action" data-loop-source="${esc(source)}" type="button">Open record ↗</button>` : ""}</li>`; }).join("");
  $("#agentic-loop").querySelectorAll("[data-loop-source]").forEach(button => button.addEventListener("click", () => openDocument(button.dataset.loopSource)));
  const storyCard = (key, tone) => { const card = presentation.story?.[key] || {}; const source = sourceAction(card.source_ids); return `<article class="story-card ${esc(tone)}"><p class="eyebrow">${esc(key.replaceAll("_", " "))}</p><h3>${esc(card.title || "Not recorded")}</h3><p>${esc(card.text || "No source-backed observation is available yet.")}</p>${source ? `<button type="button" data-story-source="${esc(source)}">Open supporting record ↗</button>` : ""}</article>`; };
  $("#story-evolution").innerHTML = storyCard("evolution", "evolution");
  $("#story-cards").innerHTML = ["important_now", "urgency", "next_action"].map((key, index) => storyCard(key, ["importance", "urgency", "next"][index])).join("");
  $(".project-story-panel").querySelectorAll("[data-story-source]").forEach(button => button.addEventListener("click", () => openDocument(button.dataset.storySource)));
  const renderRecentStory = () => {
    const moments = timeline.filter(item => item.lane === "event" || item.lane === "commit").slice(0, 3).reverse();
    $("#recent-story").innerHTML = moments.map(item => { const source = item.source_id || (item.refs || []).map(sourceIdForRef).find(Boolean); return `<article class="recent-moment"><time title="${esc(item.when)}">${esc(formatTime(item.when))}</time><span class="lane ${esc(item.lane)}">${esc(item.label)}</span><strong>${esc(eventTitle(item))}</strong>${item.summary && item.summary !== item.title ? `<p>${esc(item.summary)}</p>` : ""}${source ? `<button type="button" data-recent-source="${esc(source)}">Open source ↗</button>` : ""}</article>`; }).join("") || "<div class=\"empty\">No recent knowledge or Git events recorded. Capture a first timeline event to begin the story.</div>";
    $("#recent-story").querySelectorAll("[data-recent-source]").forEach(button => button.addEventListener("click", () => openDocument(button.dataset.recentSource)));
  };
  const renderTimeline = () => { const spine = $("#time-spine"); spine.hidden = !showFullTimeline; $("#timeline-toggle").textContent = showFullTimeline ? "Hide audit timeline" : "Open audit timeline"; spine.innerHTML = timeline.map(item => `<div class="time-row"><time title="${esc(item.when)}">${esc(formatTime(item.when))}</time><span class="lane ${esc(item.lane)}">${esc(item.label)}</span><div class="time-summary"><strong>${esc(eventTitle(item))}</strong>${item.summary && item.summary !== item.title ? `<details class="time-details"><summary>Read event note</summary><p>${esc(item.summary)}</p></details>` : ""}</div></div>`).join("") || "<div class=\"empty\">No timeline data recorded.</div>"; };
  $("#time-mode").addEventListener("click", event => { utc = !utc; event.currentTarget.textContent = utc ? "UTC time" : "Local time"; renderRecentStory(); renderTimeline(); });
  $("#timeline-toggle").addEventListener("click", () => { showFullTimeline = !showFullTimeline; renderTimeline(); }); renderRecentStory(); renderTimeline();
  const formatBytes = value => compact.format((Number(value) || 0) / 1024) + " KiB";
  const renderPulse = () => {
    const commits = pulse.commits || [];
    const working = pulse.working_tree || {};
    $("#pulse-summary").innerHTML = `<p>${esc(pulse.summary || "No committed Git history is available yet.")}</p><div class="pulse-stats"><span><b>${full.format(commits.length)}</b> committed snapshots</span><span><b>${formatBytes(working.footprint?.tracked_bytes)}</b> current tracked tree</span><span><b>${full.format(working.change?.files || 0)}</b> working-tree files changed${working.dirty ? "" : " · clean"}</span></div>`;
    $("#pulse-details").innerHTML = commits.map(item => { const change = item.change || {}, footprint = item.footprint || {}; return `<article><time>${esc(formatTime(item.when))}</time><strong>${esc(item.summary || "Recorded commit")}</strong><p>${full.format(change.files || 0)} files · +${full.format(change.insertions || 0)} / −${full.format(change.deletions || 0)} · ${formatBytes(footprint.tracked_bytes)}</p></article>`; }).join("") || "<p class=\"empty-value\">No committed snapshots are available. The current working tree is shown above when present.</p>";
    if (!window.echarts || !commits.length) { $("#pulse-chart").innerHTML = "<div class=\"chart-fallback\">Committed change and footprint data will appear after Git history is available.</div>"; return; }
    const chart = echarts.init($("#pulse-chart"), null, {renderer: "svg"});
    const labels = commits.map(item => new Date(item.when).toLocaleDateString(undefined, {month: "short", day: "numeric"}));
    const tooltip = params => { const index = params[0]?.dataIndex; const item = commits[index] || {}; const change = item.change || {}, footprint = item.footprint || {}; return `<strong>${esc(item.summary || "Recorded commit")}</strong><br>${esc(formatTime(item.when))}<br>${full.format(change.files || 0)} files · +${full.format(change.insertions || 0)} / −${full.format(change.deletions || 0)}<br>Tracked: ${formatBytes(footprint.tracked_bytes)} · Knowledge: ${formatBytes(footprint.knowledge_bytes)}`; };
    chart.setOption({
      animation: !matchMedia("(prefers-reduced-motion: reduce)").matches,
      grid: {left: 48, right: 60, top: 28, bottom: 34}, tooltip: {trigger: "axis", confine: true, formatter: tooltip},
      xAxis: {type: "category", data: labels, axisLabel: {color: "#9dbcd1"}, axisLine: {lineStyle: {color: "rgba(149,205,245,.18)"}}, axisTick: {show: false}},
      yAxis: [{type: "value", name: "lines", axisLabel: {color: "#9dbcd1"}, splitLine: {lineStyle: {color: "rgba(149,205,245,.1)"}}}, {type: "value", name: "KiB", axisLabel: {color: "#9dbcd1", formatter: value => compact.format(value / 1024)}, splitLine: {show: false}}],
      series: [
        {name: "Insertions", type: "bar", stack: "change", data: commits.map(item => item.change?.insertions || 0), itemStyle: {color: "#1e9fff"}, emphasis: {focus: "series"}},
        {name: "Deletions", type: "bar", stack: "change", data: commits.map(item => -(item.change?.deletions || 0)), itemStyle: {color: "#ff7f9f"}, emphasis: {focus: "series"}},
        {name: "Tracked footprint", type: "line", yAxisIndex: 1, showSymbol: false, data: commits.map(item => item.footprint?.tracked_bytes || 0), lineStyle: {color: "#5fc4ff", width: 2}, areaStyle: {color: "rgba(95,196,255,.08)"}},
        {name: "Knowledge footprint", type: "line", yAxisIndex: 1, showSymbol: false, data: commits.map(item => item.footprint?.knowledge_bytes || 0), lineStyle: {color: "#9fb5ff", width: 2, type: "dashed"}},
      ],
    });
    new ResizeObserver(() => chart.resize()).observe($("#pulse-chart"));
  };
  const estimateExample = {delivery_estimate: {schema: "clineflow-dashboard-delivery-estimate/v1", agent: {name: "Agent", model: "model-id", configuration_label: "Safe configuration summary"}, constants: {currency: "USD", loaded_hourly_rate: 0, baseline_hours: 0, current_direct_cost: 0, ai_without_clineflow: {effort_multiplier: 1, direct_cost: 0}, no_ai: {effort_multiplier: 1, direct_cost: 0}}, perspective: "Estimated planning perspective.", rationale: "Why these assumptions fit the source facts.", source_ids: ["canonical-document-id"]}};
  const estimateInstruction = `Add a delivery_estimate object to the agent insights JSON, then regenerate with:\n\n./.clineflow/bin/dashboard generate --insights <insights.json>\n\nRequired shape:\n${JSON.stringify(estimateExample, null, 2)}`;
  const renderDeliveryEstimate = () => {
    const target = $("#delivery-estimate");
    if (!estimate || !target) return;
    const money = new Intl.NumberFormat(undefined, {style: "currency", currency: estimate.currency, maximumFractionDigits: 0});
    const cards = (estimate.scenarios || []).map(item => `<article class="estimate-card ${esc(item.id)}"><span class="label">${esc(item.label)}</span><strong>${full.format(item.estimated_hours)} h</strong><p>${esc(money.format(item.estimated_cost))}</p><small>${item.delta_hours >= 0 ? "+" : ""}${full.format(item.delta_hours)} h · ${item.delta_cost >= 0 ? "+" : ""}${esc(money.format(item.delta_cost))} vs current</small></article>`).join("");
    target.innerHTML = `<p class="estimate-disclaimer">${esc(estimate.disclaimer)}</p><div class="estimate-layout"><div class="estimate-cards">${cards}</div><div id="estimate-chart" class="chart estimate-chart" role="img" aria-label="Estimated engineering hours and modeled cost by delivery scenario"></div></div><article class="estimate-perspective"><p class="eyebrow">Agent perspective</p><strong>${esc(estimate.perspective)}</strong><p>${esc(estimate.rationale)}</p></article><details class="estimate-inputs"><summary>Reference inputs</summary><dl><div><dt>Agent</dt><dd>${esc(estimate.agent.name)} · ${esc(estimate.agent.model)}</dd></div><div><dt>Configuration</dt><dd>${esc(estimate.agent.configuration_label)}</dd></div><div><dt>Baseline</dt><dd>${full.format(estimate.reference_inputs.baseline_hours)} h at ${esc(money.format(estimate.reference_inputs.loaded_hourly_rate))}/h</dd></div></dl></details><button class="text-action" id="estimate-how" type="button">How to revise estimate ↗</button>`;
    if (window.echarts) { const chart = echarts.init($("#estimate-chart"), null, {renderer: "svg"}); chart.setOption({animation: !matchMedia("(prefers-reduced-motion: reduce)").matches, grid: {left: 58, right: 30, top: 28, bottom: 40}, tooltip: {trigger: "item", formatter: point => `<strong>${esc(point.data.label)}</strong><br>${full.format(point.data.value[0])} h · ${esc(money.format(point.data.value[1]))}`}, xAxis: {name: "estimated hours", type: "value", axisLabel: {color: "#9dbcd1"}, splitLine: {lineStyle: {color: "rgba(149,205,245,.1)"}}}, yAxis: {name: estimate.currency, type: "value", axisLabel: {color: "#9dbcd1", formatter: value => compact.format(value)}, splitLine: {lineStyle: {color: "rgba(149,205,245,.1)"}}}, series: [{type: "scatter", symbolSize: 18, label: {show: true, formatter: point => point.data.label, position: "top", color: "#eaf6ff"}, data: estimate.scenarios.map((item, index) => ({label: item.label, value: [item.estimated_hours, item.estimated_cost], itemStyle: {color: ["#1e9fff", "#5fc4ff", "#ffc96b"][index]}}))}]}); new ResizeObserver(() => chart.resize()).observe($("#estimate-chart")); }
  };
  const estimateModal = $("#estimate-modal");
  const openEstimateModal = () => { estimateModal.innerHTML = `<form method="dialog" class="modal-head"><div><p class="eyebrow">Revision instructions</p><h2>How to revise estimate</h2><p>Reports are immutable planning views. Revise the agent-supplied insights JSON, then regenerate the report.</p></div><button class="text-action" aria-label="Close">Close</button></form><pre class="agent-prompt">${esc(estimateInstruction)}</pre>`; estimateModal.showModal(); };
  renderPulse(); renderDeliveryEstimate(); $("#estimate-how")?.addEventListener("click", openEstimateModal);
  const recordFields = item => (item.fields || []).length ? `<dl class="record-fields">${item.fields.map(field => `<div><dt>${esc(field.label)}</dt><dd>${esc(field.value)}</dd></div>`).join("")}</dl>` : "";
  const expandableDetail = item => item.detail && item.detail !== item.summary ? `<details class="record-detail"><summary>Read full record</summary><p>${esc(item.detail)}</p></details>` : "";
  const renderSignalRows = (element, items, empty) => { element.innerHTML = items.map(item => `<article class="decision-row"><span class="label">${esc(item.kind || "Recorded fact")}</span><strong>${esc(item.title || statementText(item.text || item))}</strong>${item.summary ? `<p class="record-summary">${esc(item.summary)}</p>` : ""}${recordFields(item)}${expandableDetail(item)}${item.why ? `<p><b>Why it matters:</b> ${esc(item.why)}</p>` : ""}${item.next ? `<p><b>Next move:</b> ${esc(item.next)}</p>` : ""}${sourceAction(item.source_ids) ? `<button class="text-action" data-source="${esc(sourceAction(item.source_ids))}" type="button">Open record ↗</button>` : ""}</article>`).join("") || `<div class="empty compact-empty">${esc(empty)}</div>`; element.querySelectorAll("[data-source]").forEach(button => button.addEventListener("click", () => openDocument(button.dataset.source))); };
  renderSignalRows($("#attention"), presentation.decisions || [], "No unresolved decisions or proof gaps are recorded."); renderSignalRows($("#evidence"), presentation.evidence || [], "No structured verification evidence is recorded yet.");
  const renderDocuments = query => { const needle = String(query || "").toLowerCase().trim(); const visible = docs.filter(doc => (activeFilter === "all" || doc.kind === activeFilter) && (!needle || `${doc.title} ${doc.description} ${doc.raw}`.toLowerCase().includes(needle))); $("#document-list").innerHTML = visible.map(doc => `<button class="document-button ${doc.id === selectedDocument ? "active" : ""}" data-document="${esc(doc.id)}" type="button"><span class="document-kind">${esc(doc.kind)}</span><strong>${esc(doc.title)}</strong><small>${esc(doc.path)}</small></button>`).join("") || "<div class=\"empty compact-empty\">No matching knowledge source.</div>"; $("#document-list").querySelectorAll("[data-document]").forEach(button => button.addEventListener("click", () => openDocument(button.dataset.document))); };
  const guidedHtml = guided => (guided?.sections || []).map(section => {
    if (section.type === "list") return `<section class="guided-section"><h4>${esc(section.label)}</h4><div class="guided-list">${(section.items || []).map(item => `<article><strong>${esc(item.title)}</strong>${item.summary ? `<p>${esc(item.summary)}</p>` : ""}${item.fields?.length ? `<dl class="record-fields">${item.fields.map(field => `<div><dt>${esc(field.label)}</dt><dd>${esc(field.value)}</dd></div>`).join("")}</dl>` : ""}${item.detail && item.detail !== item.summary ? `<details class="record-detail"><summary>Read full record</summary><p>${esc(item.detail)}</p></details>` : ""}</article>`).join("") || "<p class=\"empty-value\">No entries recorded.</p>"}</div></section>`;
    if (section.type === "fields") return `<section class="guided-section"><h4>${esc(section.label)}</h4><dl class="guided-fields">${(section.items || []).map(item => `<div><dt>${esc(item.label)}</dt><dd>${esc(item.value)}</dd>${item.detail && item.detail !== item.value ? `<details><summary>Full value</summary><p>${esc(item.detail)}</p></details>` : ""}</div>`).join("")}</dl></section>`;
    return `<section class="guided-section"><h4>${esc(section.label)}</h4><p>${esc(section.value || "Not recorded.")}</p>${section.detail && section.detail !== section.value ? `<details class="record-detail"><summary>Read full value</summary><p>${esc(section.detail)}</p></details>` : ""}</section>`;
  }).join("") || "<p class=\"empty-value\">No structured content recorded.</p>";
  const renderDocumentPanel = (doc, view = "guided") => {
    if (!doc) { $("#document-body").innerHTML = "<div class=\"empty\">Select a source to inspect it.</div>"; return; }
    const tabs = [["guided", "Guided view"], ["json", "JSON"], ["source", "Source"]].map(([id, label]) => `<button class="${view === id ? "active" : ""}" data-view="${id}" type="button">${label}</button>`).join("");
    const contribution = doc.kind === "ledger" ? `This ledger contributes ${doc.title.toLowerCase()} to the active project loop.` : doc.kind === "journal" ? "This journal supplies the reasoning and implementation context behind the current narrative." : "This source supplies navigational context for the knowledge bundle.";
    const content = view === "source" ? `<pre class="source-code">${esc(doc.raw || "")}</pre>` : view === "json" ? `<pre class="source-code">${esc(JSON.stringify(doc.structured || {title: doc.title, description: doc.description}, null, 2))}</pre>` : `<section class="fact-section"><p class="eyebrow">What this contributes</p><h3>${esc(doc.title)}</h3><p class="contribution">${esc(contribution)}</p><p class="panel-copy">${esc(doc.guided?.summary || doc.description || "Read the structured source before opening raw text.")}</p>${guidedHtml(doc.guided)}</section>`;
    const repair = doc.yaml?.valid && doc.yaml.normalized ? `<button class="text-action copy-action" data-copy-normalized type="button">Copy normalized YAML</button>` : "";
    $("#document-body").innerHTML = `<div class="document-hero"><div><p class="eyebrow">${esc(doc.path)}</p><h2>${esc(doc.title)}</h2><p>Structured context first; raw source remains available for exact inspection.</p></div><span class="status ${doc.yaml?.valid === false ? "invalid" : "valid"}">${doc.yaml?.valid === false ? "YAML needs repair" : "Source ready"}</span></div><div class="document-tabs">${tabs}${repair}</div><div class="document-content">${content}</div>`;
    $("#document-body").querySelectorAll("[data-view]").forEach(button => button.addEventListener("click", () => renderDocumentPanel(doc, button.dataset.view)));
    $("[data-copy-normalized]")?.addEventListener("click", async event => { await copy(doc.yaml.normalized); event.currentTarget.textContent = "Copied normalized YAML"; });
  };
  $("#document-filters").querySelectorAll("button").forEach(button => button.addEventListener("click", () => { activeFilter = button.dataset.filter; $("#document-filters").querySelectorAll("button").forEach(item => item.classList.toggle("active", item === button)); renderDocuments($("#search").value); })); $("#search").addEventListener("input", event => renderDocuments(event.currentTarget.value));
  renderDocuments(""); const initial = docs.find(doc => doc.path.endsWith("clineflow_last_session.yml")) || docs[0]; if (initial) openDocument(initial.id);
  if (!matchMedia("(prefers-reduced-motion: reduce)").matches && window.gsap) gsap.from(".hero-main,.hero-side,.panel", {opacity: 0, y: 14, duration: .55, stagger: .035, ease: "power2.out"});
})();
